# Generated by Django 5.2.1 on 2025-05-19 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operatorManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedPinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_cod', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_cod', models.BooleanField(default=False)),
                ('city_image', models.ImageField(upload_to='cities/')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('connection_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndiaSimConstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('key', models.CharField(choices=[('local_delivery_charge', 'local_delivery_charge'), ('sim_card_charge', 'sim_card_charge'), ('special_delivery_charge', 'special_delivery_charge'), ('partial_payment', 'partial_payment'), ('in_demand', 'in_demand'), ('in_stock', 'in_stock'), ('accept_indian_order', 'accept_indian_order')], max_length=255, null=True)),
                ('value', models.CharField(max_length=1255000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('pack_amount', models.FloatField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('pack_category', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackValidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('pack_validity', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('plan_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('state_image', models.ImageField(upload_to='states/')),
                ('iso_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndiaFRCSimPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('connection', models.CharField(choices=[('Prepaid', 'Prepaid'), ('Postpaid', 'Postpaid')], default='Prepaid', max_length=30)),
                ('plan_description', models.CharField(max_length=5000)),
                ('plan_benefits', models.CharField(max_length=5000)),
                ('india_sim_url', models.CharField(blank=True, max_length=200)),
                ('talktime', models.CharField(blank=True, max_length=100, null=True)),
                ('sms', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.IntegerField(blank=True, default=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('favourite_marked', models.BooleanField(default=True)),
                ('extra_charge', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('selected_favourite', models.BooleanField(default=False)),
                ('offer_price', models.CharField(blank=True, max_length=100, null=True)),
                ('traveller_plan', models.BooleanField(default=False)),
                ('best_data_uasage', models.BooleanField(default=False)),
                ('most_affordable', models.BooleanField(default=False)),
                ('cities', models.ManyToManyField(blank=True, max_length=1000, to='indiaSimManagement.city')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_frc', to='operatorManagement.operator')),
                ('constants', models.ManyToManyField(blank=True, to='indiaSimManagement.indiasimconstants')),
                ('amount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_amount_frc', to='indiaSimManagement.packamount')),
                ('validity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sim_validity_frc', to='indiaSimManagement.packvalidity')),
                ('states', models.ManyToManyField(blank=True, to='indiaSimManagement.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiaSimManagement.state'),
        ),
    ]
