# Generated by Django 5.2.1 on 2025-05-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('Bannertitle', models.CharField(max_length=100)),
                ('Bannerimage', models.ImageField(upload_to='banners/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=4, null=True)),
                ('country_name', models.CharField(blank=True, max_length=50, null=True)),
                ('country_iso2', models.CharField(blank=True, max_length=5, null=True)),
                ('slug', models.CharField(blank=True, max_length=200, null=True)),
                ('country_image', models.CharField(blank=True, max_length=200, null=True)),
                ('country_image_2', models.ImageField(blank=True, default='', null=True, upload_to='country')),
                ('iso3', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('is_top', models.BooleanField(default=False)),
                ('is_home', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
