# Generated by Django 5.2.1 on 2025-05-19 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countryManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circle', models.CharField(blank=True, max_length=50, null=True)),
                ('bbps_coverage', models.CharField(blank=True, max_length=50, null=True)),
                ('coverage_area', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('circle_code', models.CharField(blank=True, max_length=10, null=True)),
                ('slug', models.SlugField(blank=True, max_length=10000, null=True, unique=True)),
                ('is_active_to_buy', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circle_country', to='countryManagement.country')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_image', models.ImageField(null=True, upload_to='operator/')),
                ('operator_name', models.CharField(blank=True, max_length=100, null=True)),
                ('operator_code', models.CharField(blank=True, max_length=20, null=True)),
                ('operator_type', models.CharField(choices=[('PREPAID', 'PREPAID'), ('MOBILE', 'MOBILE'), ('DTH', 'DTH'), ('POSTPAID', 'POSTPAID'), ('ELECTRICITY', 'ELECTRICITY'), ('WATER', 'WATER'), ('OTHER', 'OTHER')], default='MOBILE', max_length=20)),
                ('operator_category', models.CharField(blank=True, default='', max_length=50)),
                ('operator_source', models.CharField(default='JOLO', max_length=20)),
                ('additional_parameters', models.JSONField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_country', to='countryManagement.country')),
            ],
        ),
    ]
