# Generated by Django 5.2.1 on 2025-05-26 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildex', '0001_initial'),
        ('indiaSimManagement', '0001_initial'),
        ('operatorManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='created_at',
        ),
        migrations.AddField(
            model_name='checkout',
            name='connection_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='indiaSimManagement.connectiontype'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='operator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operatorManagement.operator'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('COD', 'Cash On Delivery'), ('PARTIAL', 'Partial Payment')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indiaSimManagement.indiafrcsimpack'),
        ),
    ]
