# Generated by Django 5.2.1 on 2025-05-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildex', '0002_remove_checkout_created_at_checkout_connection_mode_and_more'),
        ('user', '0003_userinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('COD', 'Cash On Delivery'), ('PARTIAL', 'Partial Payment')], default='FULL', max_length=50, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo'),
        ),
    ]
