# Generated by Django 5.2.1 on 2025-05-29 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildex', '0004_operator_plan_remove_payment_checkout_and_more'),
        ('user', '0003_userinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavouriteplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinfo'),
        ),
    ]
